// <auto-generated />
using System;
using GestionRestaurant.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestionRestaurant.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210428123236_update-database")]
    partial class updatedatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GestionRestaurant.Models.Consommation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Paye")
                        .HasColumnType("bit");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int>("TableCmdId")
                        .HasColumnType("int");

                    b.Property<int>("produitId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TableCmdId");

                    b.HasIndex("produitId");

                    b.ToTable("Consommations");
                });

            modelBuilder.Entity("GestionRestaurant.Models.Produit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbOfPerson")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("RevenuCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("GestionRestaurant.Models.Serveur", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Serveurs");
                });

            modelBuilder.Entity("GestionRestaurant.Models.TableCmd", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPlace")
                        .HasColumnType("int");

                    b.Property<bool>("Occupation")
                        .HasColumnType("bit");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServeurId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ServeurId");

                    b.ToTable("TableCmds");
                });

            modelBuilder.Entity("GestionRestaurant.Models.Consommation", b =>
                {
                    b.HasOne("GestionRestaurant.Models.TableCmd", "Table")
                        .WithMany("Consommations")
                        .HasForeignKey("TableCmdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionRestaurant.Models.Produit", "Produit")
                        .WithMany("Consommations")
                        .HasForeignKey("produitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("GestionRestaurant.Models.TableCmd", b =>
                {
                    b.HasOne("GestionRestaurant.Models.Serveur", "Serveur")
                        .WithMany("Tables")
                        .HasForeignKey("ServeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Serveur");
                });

            modelBuilder.Entity("GestionRestaurant.Models.Produit", b =>
                {
                    b.Navigation("Consommations");
                });

            modelBuilder.Entity("GestionRestaurant.Models.Serveur", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("GestionRestaurant.Models.TableCmd", b =>
                {
                    b.Navigation("Consommations");
                });
#pragma warning restore 612, 618
        }
    }
}
